import { test, expect } from '@/test/browser-fixtures'

test('hero and contact share compact social links and keyboard-accessible tooltips', async ({ page }) => {
  for (const locale of ['pt', 'en']) {
    await page.goto(`/${locale}`)
    const nav = page.locator('[data-social-links]').first()
    await nav.scrollIntoViewIfNeeded()
    expect(await nav.getByRole('link').evaluateAll((links) => links.map((link) => link.getAttribute('aria-label')))).toEqual([
      'GitHub', 'LinkedIn', 'X', 'Instagram', 'Medium', locale === 'pt' ? 'Currículo' : 'Résumé',
    ])
    await expect(nav.getByRole('link', { name: 'Instagram', exact: true })).toHaveAttribute('href', 'https://www.instagram.com/mateus.fneiva')
    await expect(nav.getByRole('link').last()).toHaveAttribute('href', '/resume.pdf')
    const github = nav.getByRole('link', { name: 'GitHub', exact: true })
    await github.focus()
    const tooltip = page.locator('[data-custom-tooltip]')
    await expect(tooltip).toBeVisible()
    await expect(tooltip).toContainText('GitHub')
    await expect(github).toHaveAttribute('aria-describedby', /tooltip-/)
    const bounds = await tooltip.boundingBox()
    expect(bounds!.x).toBeGreaterThanOrEqual(0)
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(page.viewportSize()!.width)
    await page.keyboard.press('Escape')
    await expect(tooltip).toHaveCount(0)
    await expect(github).toBeFocused()
    const contact = page.locator('#contact [data-social-links]')
    await expect(contact.getByRole('link')).toHaveCount(6)
    await expect(contact).not.toContainText('GitHub')
    const contactResume = contact.getByRole('link').last()
    await contactResume.focus()
    await expect(tooltip).toContainText(locale === 'pt' ? 'Abrir currículo em PDF' : 'Open résumé PDF')
    await page.keyboard.press('Escape')
    await expect(tooltip).toHaveCount(0)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
  }
})

test('social icon hover changes only the icon color while the tooltip animates', async ({ page, isMobile }) => {
  test.skip(isMobile, 'Hover requires a fine pointer.')
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/pt')
  await page.evaluate(() => document.fonts.ready)
  await expect(page.locator('[data-initial-loading]')).toHaveCount(0)
  await expect(page.locator('[data-hero-copy]')).toHaveCSS('opacity', '1')
  await expect.poll(() => page.locator('[data-hero-copy]').evaluate((node) => new DOMMatrix(getComputedStyle(node).transform).m42)).toBe(0)
  const link = page.locator('[data-social-links]').first().getByRole('link', { name: 'LinkedIn', exact: true })
  await link.scrollIntoViewIfNeeded()
  await page.mouse.move(0, 0, { steps: 8 })
  const before = await link.evaluate((node) => ({ background: getComputedStyle(node).backgroundColor, transform: getComputedStyle(node).transform }))
  const icon = link.locator('[data-social-icon]')
  const color = await icon.evaluate((node) => getComputedStyle(node).color)
  await link.hover()
  await expect(page.locator('[data-custom-tooltip]')).toHaveCSS('opacity', '1')
  await expect.poll(() => icon.evaluate((node) => getComputedStyle(node).color)).not.toBe(color)
  await expect.poll(() => icon.evaluate((node) => new DOMMatrix(getComputedStyle(node).transform).m42)).toBeCloseTo(-3, 1)
  expect(await link.evaluate((node) => ({ background: getComputedStyle(node).backgroundColor, transform: getComputedStyle(node).transform }))).toEqual(before)
  await page.mouse.move(0, 0, { steps: 8 })
  await expect(page.locator('[data-custom-tooltip]')).toHaveCount(0)
})

test('tooltip follows the mouse and stays inside the viewport', async ({ page, isMobile }) => {
  test.skip(isMobile, 'Mouse tracking requires a fine pointer.')
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/pt')
  await page.evaluate(() => document.fonts.ready)
  await expect(page.locator('[data-initial-loading]')).toHaveCount(0)
  await expect.poll(() => page.locator('[data-hero-copy]').evaluate((node) => new DOMMatrix(getComputedStyle(node).transform).m42)).toBe(0)
  const link = page.locator('[data-social-links]').first().getByRole('link', { name: 'Instagram', exact: true })
  await link.scrollIntoViewIfNeeded()
  const bounds = await link.boundingBox()
  await page.mouse.move(bounds!.x + 8, bounds!.y + 20)
  const tooltip = page.locator('[data-custom-tooltip]')
  await expect(tooltip).toHaveCSS('opacity', '1')
  const first = await tooltip.boundingBox()
  await page.mouse.move(bounds!.x + 30, bounds!.y + 20, { steps: 4 })
  await expect.poll(async () => (await tooltip.boundingBox())!.x).toBeGreaterThan(first!.x + 10)
  const current = await tooltip.boundingBox()
  expect(current!.x).toBeGreaterThanOrEqual(0)
  expect(current!.x + current!.width).toBeLessThanOrEqual(page.viewportSize()!.width)
})

test('activating an external link does not leave the tooltip behind when returning to the tab', async ({ page, context }) => {
  await context.route('https://github.com/mateusneiva', (route) => route.fulfill({ contentType: 'text/html', body: '<!doctype html><title>Profile</title><p>Profile</p>' }))
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/pt')
  await expect(page.locator('[data-initial-loading]')).toHaveCount(0)
  const link = page.locator('[data-social-links]').first().getByRole('link', { name: 'GitHub', exact: true })
  await link.scrollIntoViewIfNeeded()
  await link.hover()
  await expect(page.locator('[data-custom-tooltip]')).toHaveCSS('opacity', '1')
  const opened = page.waitForEvent('popup')
  await link.click()
  const popup = await opened
  await popup.waitForLoadState()
  await page.bringToFront()
  await expect(page.locator('[data-custom-tooltip]')).toHaveCount(0)
  await popup.close()
})
