import { test, expect } from '@/test/browser-fixtures'

test('sun/moon button switches themes directly, supports keyboard and persists the choice', async ({ page }) => {
  await page.goto('/pt')
  const width = await page.evaluate(() => document.documentElement.clientWidth)
  const toggle = page.getByRole('button', { name: 'Alternar tema', exact: true })
  await expect(toggle).toBeEnabled()
  await expect(toggle).toHaveCSS('width', '32px')
  await expect(toggle.locator('svg')).toHaveCSS('width', '20px')
  await toggle.hover()
  await expect(page.locator('[data-custom-tooltip]')).toHaveCount(0)
  await expect(toggle).toHaveAttribute('aria-pressed', 'true')
  await toggle.click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await expect(toggle).toHaveAttribute('aria-pressed', 'false')
  await expect(page.getByRole('menu')).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.clientWidth)).toBe(width)
  await toggle.focus()
  await page.keyboard.press('Space')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(toggle).toHaveAttribute('aria-pressed', 'true')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(toggle).toHaveAttribute('aria-pressed', 'true')
})

test('initial theme follows the device until an explicit choice is made', async ({ page }) => {
  await page.emulateMedia({ colorScheme: 'dark' })
  await page.goto('/pt')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.emulateMedia({ colorScheme: 'light' })
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.getByRole('button', { name: 'Alternar tema', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.emulateMedia({ colorScheme: 'light' })
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
})

test('theme choice survives locale changes without client script warnings', async ({ page }) => {
  await page.goto('/pt')
  await page.getByRole('button', { name: 'Alternar tema', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  for (const locale of ['en', 'pt', 'en', 'pt']) {
    await page.getByRole('link', { name: locale.toUpperCase(), exact: true }).click()
    await expect(page).toHaveURL(`/${locale}`)
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
    await expect(page.getByRole('button', { name: locale === 'pt' ? 'Alternar tema' : 'Toggle theme', exact: true })).toHaveAttribute('aria-pressed', 'false')
    await expect(page.locator('script[src="/theme-init.js"]')).toHaveCount(1)
  }
})

test('sun morphs into the moon using the supplied Around design', async ({ page }, testInfo) => {
  await page.emulateMedia({ colorScheme: 'light', reducedMotion: 'no-preference' })
  await page.goto('/pt')
  const toggle = page.getByRole('button', { name: 'Alternar tema', exact: true })
  await expect(toggle).toBeEnabled()
  const path = toggle.locator('clipPath path')
  await expect(path).toHaveAttribute('d', 'M0 0 h42 v30 a1 1 0 0 0 -16 13 H0 Z')
  await toggle.click()
  await expect(toggle).toHaveAttribute('data-toggled', 'true')
  await expect(path).toHaveAttribute('d', 'M-12 -14 h42 v30 a1 1 0 0 0 -16 13 H0 Z')
  await expect.poll(() => toggle.locator('svg > g > circle').first().evaluate((node) => new DOMMatrix(getComputedStyle(node).transform).a)).toBeCloseTo(1.4, 1)
  await expect.poll(() => toggle.locator('clipPath').evaluate((node) => new DOMMatrix(getComputedStyle(node).transform).b)).toBeCloseTo(-1, 2)
  await toggle.screenshot({ path: testInfo.outputPath('moon-toggle.png') })
  await toggle.click()
  await expect(path).toHaveAttribute('d', 'M0 0 h42 v30 a1 1 0 0 0 -16 13 H0 Z')
  await expect.poll(() => toggle.locator('clipPath').evaluate((node) => new DOMMatrix(getComputedStyle(node).transform).b)).toBeCloseTo(0, 2)
  await toggle.screenshot({ path: testInfo.outputPath('sun-toggle.png') })
})

test('dark mode is revealed left to right without moving the layout', async ({ page }) => {
  await page.emulateMedia({ colorScheme: 'light', reducedMotion: 'no-preference' })
  await page.goto('/pt')
  await expect(page.locator('[data-initial-loading]')).toHaveCount(0)
  const before = await page.locator('main').boundingBox()
  await page.getByRole('button', { name: 'Alternar tema', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect.poll(() => page.evaluate(() => document.getAnimations().some((animation) => animation instanceof CSSAnimation && animation.animationName === 'theme-reveal-right'))).toBe(true)
  await expect(page.locator('html')).not.toHaveAttribute('data-theme-reveal')
  const after = await page.locator('main').boundingBox()
  expect(after!.x).toBeCloseTo(before!.x, 0)
  expect(after!.width).toBeCloseTo(before!.width, 0)
})

test('theme remains functional when view transitions are unsupported', async ({ page }) => {
  await page.addInitScript(() => Object.defineProperty(document, 'startViewTransition', { configurable: true, value: undefined }))
  await page.emulateMedia({ colorScheme: 'light', reducedMotion: 'no-preference' })
  await page.goto('/pt')
  await page.getByRole('button', { name: 'Alternar tema', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.locator('html')).not.toHaveAttribute('data-theme-reveal')
  await expect(page.locator('html')).not.toHaveAttribute('data-theme-fade')
})
